### PR TITLE
Control applier handle both number and string values

### PR DESCRIPTION
**Pull request by rbapin**
Ветка создана заново, так как в предыдущей реализации была допущена ошибка. Плюс учтены замечания от sin@

### CODE REVIEW

**Comment by mastersin** [comment]
Во время получения строки - ошибка:
`2020-03-03 17:37:16:Error occured while running applier: 'str' object has no attribute 'decode'`

**Comment by rbapin** [comment]
> Во время получения строки - ошибка:
> `2020-03-03 17:37:16:Error occured while running applier: 'str' object has no attribute 'decode'`

**Comment by rbapin** [comment]
Пофикшено

**Comment by mastersin** [comment]
Да, вот так оно работает:
`2020-03-03 23:10:52:Applying computer part of settings
2020-03-03 23:10:52:Working with systemd unit oddjobd.service
2020-03-03 23:10:52:Working with systemd unit sshd.service
2020-03-03 23:10:52:Working with systemd unit gpupdate.service
2020-03-03 23:10:52:Starting systemd unit: oddjobd.service
2020-03-03 23:10:52:Starting systemd unit: sshd.service
2020-03-03 23:10:52:Starting systemd unit: gpupdate.service
2020-03-03 23:10:52:Unable to start systemd unit gpupdate.service
2020-03-03 23:10:52:Working with control sshd-gssapi-auth
2020-03-03 23:10:52:Working with control ssh-gssapi-auth
2020-03-03 23:10:52:Working with control sshd-allow-groups
2020-03-03 23:10:52:Working with control sshd-allow-groups-list with string value
2020-03-03 23:10:52:Setting control sshd-gssapi-auth to enabled
2020-03-03 23:10:52:Setting control ssh-gssapi-auth to enabled
2020-03-03 23:10:52:Setting control sshd-allow-groups to enabled
2020-03-03 23:10:52:Setting control sshd-allow-groups-list to wheelonly
2020-03-03 23:10:52:Generated file /etc/polkit-1/rules.d/99-gpoa_disk_permissions.rules with arguments {'Deny_All': 0}
2020-03-03 23:10:52:Wrote Firefox preferences to /usr/lib64/firefox/distribution/policies.json
2020-03-03 23:10:52:Chromium policy 'HomepageLocation' set to about:blank
2020-03-03 23:10:52:Wrote Chromium preferences to /etc/chromium/policies/managed/policies.json
2020-03-03 23:10:52:No shortcuts to process for S-1-5-21-0-0-0-0`

А вот так отваливается в случае ошибки:
`2020-03-03 23:11:39:Applying computer part of settings
2020-03-03 23:11:39:Working with systemd unit oddjobd.service
2020-03-03 23:11:39:Working with systemd unit sshd.service
2020-03-03 23:11:39:Working with systemd unit gpupdate.service
2020-03-03 23:11:39:Starting systemd unit: oddjobd.service
2020-03-03 23:11:39:Starting systemd unit: sshd.service
2020-03-03 23:11:39:Starting systemd unit: gpupdate.service
2020-03-03 23:11:39:Unable to start systemd unit gpupdate.service
2020-03-03 23:11:39:Working with control sshd-gssapi-auth
2020-03-03 23:11:39:Working with control ssh-gssapi-auth
2020-03-03 23:11:39:Working with control sshd-allow-groups
2020-03-03 23:11:39:Working with control sshd-allow-groups-list with string value
2020-03-03 23:11:39:Setting control sshd-gssapi-auth to enabled
2020-03-03 23:11:39:Setting control ssh-gssapi-auth to enabled
2020-03-03 23:11:39:Setting control sshd-allow-groups to enabled
2020-03-03 23:11:39:Error occured while running applier: wheelonl is not in possible values for control sshd-allow-groups-list`

А должно выдать предупреждение и продолжить.

**Comment by rbapin** [comment]
Исправлено для обоих вариантов: чисел и строк

**Pull request merged**
